/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/carpet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function carpet(props) {
  const { nodes, materials } = useGLTF('models/carpet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['982665']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('models/carpet.glb')
