/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/carpet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Carpet(props) {
  const { nodes, materials } = useGLTF('models/carpet.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}  position={[1, -1.45, 0]}  rotation-x={-Math.PI / -2.5} rotation-z={-Math.PI / 1.6} >
        <mesh geometry={nodes.Object_16.geometry} material={materials['982665']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('models/carpet.glb')
