/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/computer.glb 
*/

import React, { useState, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

export function Computer(props) {
  const { nodes, materials } = useGLTF('models/computer.glb');
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.scrollY;
      if (scrollY > 100) { // Adjust this threshold as needed
        setVisible(false);
      } else {
        setVisible(true);
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    visible && (
      <group {...props} dispose={null}>
        <group scale={0.001}>
          <group position={[1100, 700, -82.657]} rotation={[-0.229, 2.2, 0]} scale={250}>
            <mesh geometry={nodes.Plane001_digital_display_sides_0.geometry} material={materials['digital_display_sides.001']} />
            <mesh geometry={nodes.Plane001_digital_displays_0.geometry} material={materials['digital_displays.001']} />
          </group>
        </group>
      </group>
    )
  );
}

useGLTF.preload('models/computer.glb');

