/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/holographic_computer.glb 
Author: Tefloman (https://sketchfab.com/lucas.avendano13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/holographic-computer-0a51f98ffeab420889c0c03b88fa2f42
Title: Holographic Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HoloComputer(props) {
  const { nodes, materials } = useGLTF('models/holographic_computer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.15}>
        <group position={[0, 0, 0.638]} >
          <mesh geometry={nodes.Circle_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Circle_2.geometry} material={materials['Area.001']} />
        </group>
        <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.005']} scale={10} />
        <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.004']} position={[0, 0, 6.131]} rotation={[Math.PI / 2, 0, 0]} scale={3.284} />
        <mesh geometry={nodes['Keyboard-ref2_0'].geometry} material={materials['Keyboard-ref2']} position={[0, -3.022, 0.252]} scale={3.177} />
      </group>
    </group>
  )
}

useGLTF.preload('models/holographic_computer.glb')
